name: 'Ansible Chatbot Evaluations Workflow'

on:
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up promptfoo
        run: npm install -g promptfoo

      - name: Run Ansible Chatbot evaluation
        run: npx promptfoo@latest eval -c ansible-chatbot-eval.yaml -o ansible-chatbot-eval-out.json -o ansible-chatbot-eval-out.html
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          CHATBOT_STAGE_TOKEN: ${{ secrets.CHATBOT_STAGE_TOKEN }}

      # TODO: Upload where?
#      - name: Upload evaluation output
#        uses: actions/upload-artifact@v4
#        with:
#          name: ansible-chatbot-eval-out
#          path: ansible-chatbot-eval-out.json
#        # Use always() to always run this step to publish test results when there are test failures
#        if: ${{ always() }}
