name: 'Granite Model Family Evaluations Workflow'

on:
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up promptfoo
        run: npm install -g promptfoo

      - name: Run Granite Models Family evaluation
        run: npx promptfoo@latest eval -c granite-family-eval.yaml -o granite-family-eval-out.json
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          CHATBOT_STAGE_TOKEN: ${{ secrets.CHATBOT_STAGE_TOKEN }}
          GRANITE_3_0_API_TOKEN: ${{ secrets.GRANITE_3_0_API_TOKEN }}
          GRANITE_3_1_API_TOKEN: ${{ secrets.GRANITE_3_1_API_TOKEN }}

      # TODO: Upload where?
#      - name: Upload evaluation output
#        uses: actions/upload-artifact@v4
#        with:
#          name: granite-family-eval-out
#          path: granite-family-eval-out.json
#        # Use always() to always run this step to publish test results when there are test failures
#        if: ${{ always() }}
